# -*- coding: utf-8 -*-
"""BLaIR_100k.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPDnJV_PerH8faiNgZJlliwXjqc4s2nN
"""

!git clone https://github.com/nmcheung04/AmazonReviews2023_Forked.git

!pip install torch transformers datasets

!pip install recbole

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/AmazonReviews2023_Forked/seq_rec_results/dataset/
!python process_amazon_2023_100k.py --domain Electronics --device cuda:0 --plm hyp1231/blair-roberta-base

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/AmazonReviews2023_Forked/seq_rec_results/
!python run.py -m UniSRec -d Electronics --gpu_id=0